# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
# 
version: 2.1
jobs:
        build:
                # Specify the Xcode version to use
                macos:
                        xcode: "11.3.0"
                shell: /bin/bash --login -eo pipefail
                environment:
                        GENERAL_CACHE_KEY: "QuickBrickOfficialPlugins_Cache_1.1.1"
                        PROJECT_NAME: "QuickBrickOfficialPlugins"
                        SCHEME_NAME: "QuickBrickOfficialPlugins"
                        PROJECT_PATH: "QuickBrickOfficialPlugins"
                        HOMEBREW_NO_AUTO_UPDATE: "1"

                working_directory: ~/QuickBrickOfficialPlugins
                steps:
                        #Hack general caching until circle does not support global env variables
                        - run: echo "$GENERAL_CACHE_KEY" > ~/_caching_file

                        - run:
                                  name: Ruby - version
                                  command: ruby -v

                        # Prepere Git
                        - restore_cache:
                                  keys:
                                          - GIT-{{ checksum "~/_caching_file" }}-{{ .Branch }}-{{ .Revision }}
                                          - GIT-{{ checksum "~/_caching_file" }}-{{ .Branch }}-
                                          - GIT-{{ checksum "~/_caching_file" }}-

                        - checkout

                        - save_cache:
                                  name: Git - save cache
                                  key: GIT-{{ checksum "~/_caching_file" }}-{{ .Branch }}-{{ .Revision }}
                                  paths:
                                          - ".git"

                        - restore_cache:
                                  name: Restore npm dependencies
                                  key: YARN-{{ checksum "~/_caching_file" }}-{{ checksum "yarn.lock" }}

                        - run:
                                  name: NPM Login
                                  command: npx npm-shell-login

                        - run:
                                  name: Install node version 12.0.0
                                  command: |
                                    npm install -g n
                                    sudo n 12
                        - run:
                                  name: Install npm dependencies
                                  command: yarn

                        - save_cache:
                                  name: Saving NPM dependencies
                                  key: YARN-{{ checksum "~/_caching_file" }}-{{ checksum "yarn.lock" }}
                                  paths:
                                          - ./node_modules

                        - run:
                                  name: Homebrew tap Applicaster
                                  command: brew tap applicaster/tap

                        - run:
                                  name: Homebrew Install Zappifest
                                  command: brew install zappifest

                        - run:
                                  name: Zappifest Version
                                  command: zappifest -v

                        - run:
                                  name: Validate Frameworks
                                  command: node ./Scripts/validateExistingFrameworks.js

                        - deploy:
                                  name: Publish new or changed framework
                                  command: node ./Scripts/publishFramework.js

                        - store_test_results:
                                  path: ./CircleArtifacts/test-results

                        - store_artifacts:
                                  path: ./CircleArtifacts

                        - store_artifacts:
                                  path: ~/Library/Logs/scan
                                  destination: scan-logs

workflows:
        version: 2
        build:
                jobs:
                        - build
